thinknetica/project_trains/config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  root 'home#index'

  resources :trains
  resources :railway_stations
  resources :routes
  resources :tickets
  resources :users
  resources :wagons
  resources :seats
end

thinknetica/project_trains/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

thinknetica/project_trains/app/models/railway_station.rb
class RailwayStation < ApplicationRecord
  validates :title, presence: true

  has_many :railway_stations_routes
  has_many :routes, through: :railway_stations_routes
end

thinknetica/project_trains/app/models/railway_stations_route.rb
class RailwayStationsRoute < ApplicationRecord
  belongs_to :railway_station
  belongs_to :route
end

thinknetica/project_trains/app/models/route.rb
class Route < ApplicationRecord
  validates :name, presence: true

  has_many :trains
  has_many :railway_stations_routes
  has_many :railway_stations, through: :railway_stations_routes
end

thinknetica/project_trains/app/models/seat.rb
class Seat < ApplicationRecord
  validates :number, presence: true

  belongs_to :wagon
end

thinknetica/project_trains/app/models/ticket.rb
class Ticket < ApplicationRecord
  validates :start, presence: true
  validates :end, presence: true
  validates :name, presence: true
  validates :surname, presence: true

  belongs_to :train
  belongs_to :user
end

thinknetica/project_trains/app/models/train.rb
class Train < ApplicationRecord
  validates :number, presence: true

  belongs_to :route
  has_many :tickets
  has_many :wagons
end

thinknetica/project_trains/app/models/user.rb
class User < ApplicationRecord
  validates :login, presence: true

  has_many :tickets
end

thinknetica/project_trains/app/models/wagon.rb
class Wagon < ApplicationRecord
  validates :w_type, presence: true
  validates :number, presence: true

  belongs_to :train
  has_many :seats
end

thinknetica/project_trains/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

thinknetica/project_trains/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

thinknetica/project_trains/app/controllers/railway_stations_controller.rb
class RailwayStationsController < ApplicationController
  before_action :set_railway_station, only: [:show, :edit, :update, :destroy]

  def index
    @railway_stations = RailwayStation.all
  end

  def show
  end

  def new
    @railway_station = RailwayStation.new
  end

  def edit
  end

  def create
    @railway_station = RailwayStation.new(railway_station_params)

    if @railway_station.save
      redirect_to @railway_station
    else
      render :new
    end
  end

  def update
    if @railway_station.update(railway_station_params)
      redirect_to @railway_station
    else
      render :edit
    end
  end

  def destroy
    @railway_station.destroy
    redirect_to railway_stations_path
  end

  private

  def set_railway_station
    @railway_station = RailwayStation.find(params[:id])
  end

  def railway_station_params
    params.require(:railway_station).permit(:title)
  end
end

thinknetica/project_trains/app/controllers/routes_controller.rb
class RoutesController < ApplicationController
  before_action :set_route, only: [:show, :edit, :update, :destroy]

  def index
    @routes = Route.all
  end

  def show
  end

  def new
    @route = Route.new
  end

  def create
    @route = Route.new(route_params)

    if @route.save
      redirect_to @route
    else
      render :new
    end
  end

  def edit
  end

  def update

    if @route.update(route_params)
      redirect_to @route
    else
      render :edit
    end
  end

  def destroy
    @route.destroy
    redirect_to routes_path
  end

  private

  def set_route
    @route = Route.find(params[:id])
  end

  def route_params
    params.require(:route).permit(:name)
  end
end

thinknetica/project_trains/app/controllers/seats_controller.rb
class RoutesController < ApplicationController
  before_action :set_seat, only: [:show, :edit, :update, :destroy]

  def index
    @seats = Seat.all
  end

  def show
  end

  def new
    @seat = Seat.new
  end

  def create
    @seat = Seat.new(seat_params)

    if @seat.save
      redirect_to @seat
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @seat.update(seat_params)
      redirect_to @seat
    else
      render :edit
    end
  end

  def destroy
    @seat.destroy
    redirect_to seats_path
  end

  private

  def set_seat
    @seat = Seat.find(params[:id])
  end

  def seat_params
    params.require(:seat).permit(:number, :wagon_id)
  end
end

thinknetica/project_trains/app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]

  def index
    @tickets = Ticket.all
  end

  def show
  end

  def new
    @ticket = Ticket.new
  end

  def create
    @ticket = Ticket.new(ticket_params)

    if @ticket.save
      redirect_to @ticket
    else
      render :new
    end
  end

  def edit
  end

  def update

    if @ticket.update(ticket_params)
      redirect_to @ticket
    else
      render :edit
    end
  end

  def destroy
    @ticket.destroy
    redirect_to tickets_path
  end

  private

  def set_ticket
    @ticket = Ticket.find(params[:id])
  end

  def ticket_params
    params.require(:ticket).permit(:start, :end, :name, :surname)
  end
end

thinknetica/project_trains/app/controllers/trains_controller.rb
class TrainsController < ApplicationController
  before_action :set_train, only: [:show, :edit, :update, :destroy]

  def index
    @trains = Train.all
  end

  def show
  end

  def new
    @train = Train.new
  end

  def edit
  end

  def create
    @train = Train.new(train_params)

    if @train.save
      redirect_to @train
    else
      render :new
    end
  end

  def update
      if @train.update(train_params)
        redirect_to @train
        else
          render :edit
      end
  end

  def destroy
    @train.destroy
    redirect_to trains_url
  end

  private

  def set_train
    @train = Train.find(params[:id])
  end

  def train_params
    params.require(:train).permit(:number, :route_id)
  end
end

thinknetica/project_trains/app/controllers/users_controller.rb
class TicketsController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to @user
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to @user
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to users_path
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:login)
  end
end

thinknetica/project_trains/app/controllers/wagons_controller.rb
class WagonsController < ApplicationController
  before_action :set_wagon, only: [:show, :edit, :update, :destroy]

  def index
    @wagons = Wagon.all
  end

  def show
  end

  def new
    @wagon = Wagon.new
  end

  def create
    @wagon = Wagon.new(wagon_params)

    if @wagon.save
      redirect_to @wagon
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @wagon.update(wagon_params)
      redirect_to @wagon
    else
      render :edit
    end
  end

  def destroy
    @wagon.destroy
    redirect_to wagons_path
  end

  private

  def set_wagon
    @wagon = Wagon.find(params[:id])
  end

  def wagon_params
    params.require(:wagon).permit(:w_type, :train_id, :number, :upper_seats, :lower_seats)
  end
end

thinknetica/project_trains/app/helpers/application_helper.rb
module ApplicationHelper
end

thinknetica/project_trains/app/helpers/home_helper.rb
module HomeHelper
end

thinknetica/project_trains/app/helpers/railway_stations_helper.rb
module RailwayStationsHelper
end

thinknetica/project_trains/app/helpers/trains_helper.rb
module TrainsHelper
end

thinknetica/project_trains/app/views/home/index.html.erb
<h1>Home page</h1>

<%= link_to 'Railway stations', railway_stations_path %>
<%= link_to 'Routes', routes_path %>
<%= link_to 'Trains', trains_path %>
<%= link_to 'Tickets', tickets_path %>
<%= link_to 'Wagons', wagons_path %>

thinknetica/project_trains/app/views/railway_stations/_form.html.erb
<%= form_for(railway_station) do |f| %>
  <%= render 'common/errors', resource: @railway_station %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

    <div class="actions">
      <%= f.submit "#{ railway_station.new_record? ? 'Create' : 'Edit'}" %>
    </div>
<% end %>

thinknetica/project_trains/app/views/railway_stations/_railway_station.html.erb
<tr>
  <td><%= railway_station.title %></td>
  <td><%= link_to 'Show', railway_station %></td>
  <td><%= link_to 'Edit', edit_railway_station_path(railway_station) %></td>
  <td><%= link_to 'Destroy', railway_station, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

thinknetica/project_trains/app/views/railway_stations/edit.html.erb
<h1>Editing Railway Station</h1>

<%= render 'form', railway_station: @railway_station %>

<%= link_to 'Show', @railway_station %> |
<%= link_to 'Back', railway_stations_path %>

thinknetica/project_trains/app/views/railway_stations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Railway Stations</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%= render @railway_stations %>
  </tbody>
</table>

<br>

<%= link_to 'New Railway Station', new_railway_station_path %>

thinknetica/project_trains/app/views/railway_stations/new.html.erb
<h1>New Railway Station</h1>

<%= render 'form', railway_station: @railway_station %>

<%= link_to 'Back', railway_stations_path %>

thinknetica/project_trains/app/views/railway_stations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @railway_station.title %>
</p>

<%= link_to 'Edit', edit_railway_station_path(@railway_station) %> |
<%= link_to 'Back', railway_stations_path %>

thinknetica/project_trains/app/views/seats/_form.html.erb
<%= form_for(seat) do |f| %>
    <%= render 'common/errors', resource: @seat %>

    <div class="field">
      <%= f.label :number %>
      <%= f.text_field :number %>
    </div>

    <div class="actions">
      <%= f.submit "#{ seat.new_record? ? 'Create' : 'Edit'}" %>
    </div>
<% end %>

thinknetica/project_trains/app/views/seats/_seat.html.erb
<tr>
  <td><%= seat.number %></td>
  <td><%= link_to 'Show', seat %></td>
  <td><%= link_to 'Edit', edit_seat_path(seat) %></td>
  <td><%= link_to 'Destroy', seat, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

thinknetica/project_trains/app/views/seats/edit.html.erb
<h1>Editing Seat</h1>

<%= render 'form', seat: @seat %>

<%= link_to 'Show', @seat %> |
<%= link_to 'Back', seats_path %>

thinknetica/project_trains/app/views/seats/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Seats</h1>

<table>
  <thead>
  <tr>
    <th>Number</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
    <%= render @seats %>
  </tbody>
</table>

<br>

<%= link_to 'New Seat', new_seat_path %>

thinknetica/project_trains/app/views/seats/new.html.erb
<h1>New Seat</h1>

<%= render 'form', seat: @seat %>

<%= link_to 'Back', seats_path %>

thinknetica/project_trains/app/views/seats/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Number:</strong>
  <%= @seat.number %>
</p>

<%= link_to 'Edit', edit_seat_path(@seat) %> |
<%= link_to 'Back', seats_path %>

thinknetica/project_trains/app/views/tickets/_form.html.erb
<%= form_for(ticket) do |f| %>
    <%= render 'common/errors', resource: @ticket %>

    <!-- Start & End stations fields -->
    <div class="field">
      <table>
        <tr>
          <th><%= f.label :start %></th>
          <th><%= f.label :end %></th>
        </tr>
        <tr>
          <td><%= f.text_field :start %></td>
          <td><%= f.text_field :end %></td>
        </tr>
      </table>
    </div>

    <!-- Name & Surname fields -->
    <div class="field">
      <table>
        <tr>
          <th><%= f.label :name %></th>
          <th><%= f.label :surname %></th>
        </tr>
        <tr>
          <td><%= f.text_field :name %></td>
          <td><%= f.text_field :surname %></td>
        </tr>
      </table>
    </div>

    <!--select train field-->
    <div class="field">
      <%= f.label :train, "Current train" %>
      <%= f.collection_select :train_id, Train.all, :id, :number %>
    </div>

    <div class="actions">
      <%= f.submit "#{ ticket.new_record? ? 'Create' : 'Edit'}" %>
    </div>
<% end %>

thinknetica/project_trains/app/views/tickets/_ticket.html.erb
<tr>
  <td><%= ticket.start %></td>
  <td><%= ticket.end %></td>
  <td><%= link_to 'Show', ticket %></td>
  <td><%= link_to 'Edit', edit_ticket_path(ticket) %></td>
  <td><%= link_to 'Destroy', ticket, method: :delete, data: {confirm: 'Are you sure?'} %></td>
</tr>

thinknetica/project_trains/app/views/tickets/edit.html.erb
<h1>Editing Ticket</h1>

<%= render 'form', ticket: @ticket %>

<%= link_to 'Show', @ticket %> |
<%= link_to 'Back', tickets_path %>

thinknetica/project_trains/app/views/tickets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tickets</h1>

<table>
  <thead>
  <tr>
    <th>Start</th>
    <th>End</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
    <%= render @tickets %>
  </tbody>
</table>

<br>

<%= link_to 'New Ticket', new_ticket_path %>

thinknetica/project_trains/app/views/tickets/new.html.erb
<h1>New Ticket</h1>

<%= render 'form', ticket: @ticket %>

<%= link_to 'Back', tickets_path %>

thinknetica/project_trains/app/views/tickets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <tr>
    <th><strong>Start:</strong></th>
    <th><strong>End:</strong></th>
  </tr>
  <tr>
    <td><%= @ticket.start %></td>
    <td><%= @ticket.end %></td>
  </tr>
</p>

<%= link_to 'Edit', edit_ticket_path(@ticket) %> |
<%= link_to 'Back', tickets_path %>

thinknetica/project_trains/app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
    <%= render 'common/errors', resource: @user %>

    <div class="field">
      <%= f.label :login %>
      <%= f.text_field :login %>
    </div>

    <div class="actions">
      <%= f.submit "#{ user.new_record? ? 'Create' : 'Edit'}" %>
    </div>
<% end %>

thinknetica/project_trains/app/views/users/_user.html.erb
<tr>
  <td><%= user.name %></td>
  <td><%= link_to 'Show', user %></td>
  <td><%= link_to 'Edit', edit_user_path(user) %></td>
  <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

thinknetica/project_trains/app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

thinknetica/project_trains/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
  <tr>
    <th>Login</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
    <%= render @users %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

thinknetica/project_trains/app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

thinknetica/project_trains/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Login:</strong>
  <%= @user.login %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

thinknetica/project_trains/app/views/wagons/_form.html.erb
<%= form_for(wagon) do |f| %>
    <%= render 'common/errors', resource: @wagon %>

    <div class="field">
      <%= f.label :number %>
      <%= f.text_field :number %>
    </div>

    <div class="field">
      <%= f.radio_button :w_type, 'Second class' %>
      <%= f.label :type_second, 'Second-class sleeping carriage' %>
      <%= f.radio_button :w_type, 'Third class' %>
      <%= f.label :type_third, 'Third-class sleeping carriage' %>
    </div>

    <div class="field">
      <%= f.label :lower_seats %>
      <%= f.text_field :lower_seats %>
      <%= f.label :upper_seats %>
      <%= f.text_field :upper_seats %>
    </div>

    <div class="field">
      <%= f.label :train, "Current train" %>
      <%= f.collection_select :train_id, Train.all, :id, :number %>
    </div>

    <div class="actions">
      <%= f.submit "#{ wagon.new_record? ? 'Create' : 'Edit'}" %>
    </div>
<% end %>

thinknetica/project_trains/app/views/wagons/_wagon.html.erb
<tr>
  <td><%= wagon.number %></td>
  <td><%= link_to 'Show', wagon %></td>
  <td><%= link_to 'Edit', edit_wagon_path(wagon) %></td>
  <td><%= link_to 'Destroy', wagon, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

thinknetica/project_trains/app/views/wagons/edit.html.erb
<h1>Editing Wagon</h1>

<%= render 'form', wagon: @wagon %>

<%= link_to 'Show', @wagon %> |
<%= link_to 'Back', wagons_path %>

thinknetica/project_trains/app/views/wagons/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Wagons</h1>

<table>
  <thead>
  <tr>
    <th>Type</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
    <%= render @wagons %>
  </tbody>
</table>

<br>

<%= link_to 'New Wagon', new_wagon_path %>

thinknetica/project_trains/app/views/wagons/new.html.erb
<h1>New Wagon</h1>

<%= render 'form', wagon: @wagon %>

<%= link_to 'Back', wagons_path %>

thinknetica/project_trains/app/views/wagons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Number:</strong>
  <%= @wagon.number %>
  <br>

  <strong>Type:</strong>
  <%= @wagon.w_type %>
  <br>

  <strong>Lower seats:</strong>
  <%= @wagon.lower_seats %>
  <br>

  <strong>Upper seats:</strong>
  <%= @wagon.upper_seats %>
  <br>

  <strong>Train:</strong>
  <% if @wagon.train.present? %>
      <%= @wagon.train.number %>
  <% else %>
      Nothing
  <% end %>
  <br>
</p>

<%= link_to 'Edit', edit_wagon_path(@wagon) %> |
<%= link_to 'Back', wagons_path %>